services:
  tutorials:
    build: ./tutorials
    volumes:
      - ./tutorials:/tutorials
    ports:
      - 8001:8000
    image: tutorials:django
    container_name: tutorials_Web
    command: python manage.py runsslserver 0:8000
    restart: always
