# Generated by Django 4.0.5 on 2022-07-06 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_learned', models.DateTimeField(auto_now_add=True)),
                ('heading', models.CharField(max_length=100)),
                ('subheading', models.TextField()),
                ('footer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveSmallIntegerField(default=1)),
                ('step_name', models.CharField(max_length=100)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learned.content')),
            ],
        ),
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(max_length=100)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('text', models.TextField()),
                ('text_type', models.CharField(choices=[('NM', 'NORMAL'), ('CD', 'CODE'), ('BU', 'BULLET'), ('NT', 'NOTE')], default='NM', max_length=2)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learned.step')),
            ],
        ),
    ]
