# Generated by Django 4.0.5 on 2022-11-18 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learned', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paragraph',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='step',
            options={'ordering': ['step_number']},
        ),
    ]
